### ISSUE TITLE
Fix sdk_files.cfg

### ISSUE THREAD

**Issue by SBI-** [jazz-community/jazz-debug-environment#1]
There seems to have been a problem when creating the sdk_files.cfg. There are two paths that are mangled. Best fix for this will be to automatically generate the list from the generated jetty file.

**Comment by innerjoin** [comment]
@SBI- any update on this?

**Comment by SBI-** [comment]
It hasn't been an issue so far, which means it only concerns files that we don't use in our development workflow. This is pretty much the conclusion @rsjazz comes to in comment 68 of [Enhancement 422713](https://jazz.net/jazz/web/projects/Rational%20Team%20Concert#action=com.ibm.team.workitem.viewWorkItem&id=422713). I don't know a way of definitely knowing if a jar is necessary for our purposes. I've decided not to change a running system until we have more information.

**Comment by innerjoin** [comment]
I see, so we should keep this open as long as we don't come up with a better solution

**Comment by SBI-** [comment]
sdk_files.cfg is now generated from the files available in the sdk. This has some minor repercussions, including longer startup time and more dependency log messages, however, it also means that any changes to the sdk are automatically accounted for. I think that should close this issue for now.
