### ISSUE TITLE
Missing gradle tasks in windows

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/jazz-debug-environment#17]
Executing some gradle commands on a windows machine tells you that the execution of the task was successful, but the implementation is entirely missing, so there is nothing done while executing. This is true for the following tasks:
- `kill`
- `db`

**Comment by innerjoin** [comment]
Please check if that is still the case

**Comment by SBI-** [comment]
I have stopped developing any functionality which is platform dependent. Any features that don't have an obvious platform dependent solution will just be dropped.
