### ISSUE TITLE
Database unavailable when gradlew sets DB up

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/jazz-debug-environment#19]
If I manually extract the DB presets, the debug environment works smoothly, but if I run:
- gradlew generate
- gradlew run
The DB seems to be extracted as well, but the started RTC Jetty Server can't connect to it.

**Comment by innerjoin** [comment]
Please review if that is still the case with the latest changes

**Comment by SBI-** [comment]
I have never been able to reproduce this problem, generate and run don't touch any database files. It's probably a mismatch of the config files with the sdk version.
