### ISSUE TITLE
Linux branch

### ISSUE THREAD

**Issue by SBI-** [jazz-community/jazz-debug-environment#2]
Duplicate functionality where necessary and make the jetty configuration run on linux.

**Comment by innerjoin** [comment]
@SBI- There is a Linux branch since a few months. Is this still an open topic and if yes, what needs to be done to achieve feature parity?

**Comment by SBI-** [comment]
It works as intended for every version up to and including 6.0.4. I however have no way of verifying if this only works for me or not, so I've decided to just keep this open, guessing that I'm probably the only person actually using this.

**Comment by innerjoin** [comment]
As long as there are no reports that it doesn't work on a specific linux environment, I see no reason to keep this open as both branches have feature parity
