### ISSUE TITLE
Finish the 6.0.6 work in the gradle-init branch, clean up and release

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/jazz-debug-environment#20]
@SBI- please add me for final review

**Comment by SBI-** [comment]
I think there is still a bunch of work to be done, especially after some of the lessons we learned when 6.0.4 - 6.0.6 repeatedly broke our development work flow and tools. I'd like to take some time to implement proper improvements before rushing a new version out the door. Everything that worked under 6.0.3 works just as well now.
