### ISSUE TITLE
run_jetty.ps1 fails

### ISSUE THREAD

**Issue by keith-eberhard** [jazz-community/jazz-debug-environment#6]
[.log](https://github.com/jazz-community/jazz-debug-environment/files/1357241/default.log)

I extracted RTC-SDK-Server-6.0.3.zip to the sdk directory of the jazz-debug-environment directory.
I extracted the jre directory from JTS-CCM-keys-Win64_6.0.4.zip to the jre directory of the jazz-debug-environment directory. Since I did not extract the jre from 6.0.3, could this be the problem?

**Comment by SBI-** [comment]
A lot of the errors are normal. Running rtc applications outside of a full EE application container is a bit of a hack, so seeing a bunch of exceptions (and missing dependencies for that matter) is completely normal. "No application id has been found" is also a very generic osgi launcher error and can mean anything from "no problem" to "won't ever start"(there's more detail here: http://www.vogella.com/tutorials/EclipsePlugin/article.html#checklist-for-common-launch-problems). As both 6.0.3 and 6.0.4 run on java 7, the jre mismatch shouldn't be a problem, and I couldn't reproduce the error. However, I get a similar looking log when I don't run 'generate_jetty_config':
[bak_0.log](https://github.com/jazz-community/jazz-debug-environment/files/1358655/bak_0.log)

For comparison, this is a log after running clean and generate on a freshly checked out debug environment:

[log1.log](https://github.com/jazz-community/jazz-debug-environment/files/1358676/log1.log)
[log2.log](https://github.com/jazz-community/jazz-debug-environment/files/1358677/log2.log)

As you can see, it's also very noisy and verbose, but it works nonetheless.

**Comment by SBI-** [comment]
Issue has been resolved as mentioned in #9
