### ISSUE TITLE
How to create a development project on eclipse

### ISSUE THREAD

**Issue by keith-eberhard** [jazz-community/jazz-debug-environment#9]
Unable to add a comment on issue #6 
Get a message "You can't perform that action at this time".

I deleted my troublesome install and then installed again. This time I was able to login to the server!

I now want to create a plugin development project and start with the files from rtc-create-child-item-plugin-1.0.0.zip. Would you mind providing steps how you would do this on eclipse. What selection path would you use for creating the plugin development project.

Thanks,
Keith

**Comment by keith-eberhard** [comment]
By selection, I mean something like File > New > Project > Plug-in Development > ?

Or File > New > Plug-in Project

Or File > New > Feature Project

**Comment by SBI-** [comment]
I don't work with eclipse, so I can't really answer this question. However, jazz plugins are based on eclipse plugins and this is the default project layout used in @rsjazz 's workshop. Presumably, you should be able to create a plugin project and import the existing sources.

**Comment by innerjoin** [comment]
In general,, you could follow other extension tutorials or use the project structure of one of our plug-ins to get started.

@keith-eberhard Is there still an open issue/question from your side on this topic?
